### ISSUE TITLE
Start-up sequencing issue

### ISSUE THREAD

**Issue by funkybob** [uptick/django-dramatiq-pg#3]
There's a startup sequence issue: when django starts up, it first imports all the apps, and all of their models, then invokes the AppConfigs' `ready()` functions.

This means your code may be importing tasks indirectly, whose decorator tries to `get_broker`.

But we only register our broker in `ready()`, meaning the default RabbitMQ broker is used.

A kludgy work-around is in the dummy-broker branch, where on import we register a dummy broker which just accumulates a list of registered tasks, then provides a method to re-register (and re-validate) those tasks against our _real_ broker once we're ready.

https://github.com/uptick/django-dramatiq-pg/compare/cjm/dummy-broker

This is showing to be workable in testing, but feels very dirty and brittle to me.

**Comment by jarekwg** [comment]
How about instead of a dummy broker, just having a dummy registry? Basically the same thing, but instead of pretending to have a temporary broker, we just have a temporary dict (or similar) structure that holds all the tasks until the real broker is created and ready to register stuff against?
This would hopefully minimize any fake broker busywork?

**Comment by funkybob** [comment]
I was also considering abstracting the task registry from the broker.

Then you can create a registry, and bind a Broker to it later.

**Comment by funkybob** [comment]
Fixed with registry branch merge.
